import tkinter as tk
from tkinter import ttk
root=tk.Tk()
root.title("login")
root.geometry("1080x720")
##########################################################DATABASE CONNECTIvITY#################
#import psycopg2
#DB_NAME="try"
#DB_USER="postgres"
#DB_PASSWORD="password"
#DB_PORT="5432"
#conn=psycopg2.connect(database=DB_NAME,  user=DB_USER,  password=DB_PASSWORD,  port=DB_PORT)
#my_cursor = conn.cursor()
## create button
#def action():
#    user_name = name_var.get()
#    user_email = email_var.get()
#    user_age = age_var.get()
#    user_gender = gender_var.get()
#    user_type = usertype.get()
#    query_1 = "create table student(name char(20), email varchar(20), age char(20), gender char(20) )"
##    query_2 = "create table teacher1(name char(20), email varchar(20), age char(20), gender char(20), type char(20) )"
#    my_cursor.execute(query_1)
#    query = "insert into student values(%s,%s,%s,%s,%s)"
#    values=(user_name,user_email,user_age,user_gender)
#    conn.commit()

###############################################################################open of main window1
username = "111" 
password = "000"
user_Label=ttk.Label(root, text='Enter your ID: ')
user_Label.grid(row=0,column=0,sticky="W")
password_Label=ttk.Label(root,text='enter your password:')
password_Label.grid(row=1,column=0,sticky="W")
user_var=tk.StringVar()
user_entrybox=ttk.Entry(root, width=16,textvariable=user_var)
user_entrybox.grid(row=0,column=1,pady=4,padx=4)
password_var=tk.StringVar()
password_entrybox=ttk.Entry(root, width=16,textvariable=password_var ,show='*')
password_entrybox.grid(row=1,column=1,pady=4,padx=4)
submit_Label=ttk.Label(root,text='due you want to submit given data:')
submit_Label.grid(row=2,column=0,sticky="W") 
def trylogin(): 
    if username == user_var.get() and password == password_var.get():
        return open
    else:
        tk.messagebox.showinfo("-- ERROR --", "Please enter valid infomation!")
###############################################################################open ofwelcome window window2
def open1():
    top2=tk.Toplevel()
    top2.geometry("1080x720")
    top2.title("WELCOME TO EMPLOYEE MANAGEMENT SYSTEM ")
    top2.geometry("1080x720")
##############################################################################open of welcome of administration main windoa window3    
    def open2():
        top3=tk.Toplevel()
        top3.geometry("1080x500")
        top3.title("WELCOME TO ADMIISTRATION DASHBOARD")
        top3.geometry("1080x500")
        
###############################################################################open of administration employee window3        
        def open4():
            top3=tk.Toplevel()
            top3.geometry("1080x720")
            top3.title("WELCOME TO EMPLOYEE SHELL")
            top3.geometry("1080x720")
            #create labels.................
            name_Label1=tk.Label(top3, text='PLEASE ENTER THE DETAILS AS PER GIVEN DETAILS ...............................................................................................................................................')         
            name_Label1.grid(row=0,column=0,sticky=tk.W)
            name_Label=tk.Label(top3, text='ENTER EM. NAME: ')
            name_Label.grid(row=2,column=0,sticky=tk.W)
            gmail_Label=tk.Label(top3,text='EMAIL:')
            gmail_Label.grid(row=4,column=0,sticky=tk.W)
            age_Label=tk.Label(top3,text='AGE:')
            age_Label.grid(row=6,column=0,sticky=tk.W)
            mobile_Label=tk.Label(top3,text='MO. NUMBER:')
            mobile_Label.grid(row=8,column=0,sticky=tk.W)
            gender_Label=tk.Label(top3,text='SEX:')
            gender_Label.grid(row=10,column=0,sticky=tk.W)
            type_Label=tk.Label(top3,text='EMPLOYEE TYPE:')
            type_Label.grid(row=12,column=0,sticky=tk.W)
            option1_Label=tk.Label(top3,text='TO MAKE EMPLOYEE PERMANENT ?:')
            option1_Label.grid(row=14,column=0,sticky=tk.W)
            option_Label=tk.Label(top3,text='TO REMOVE EMPLOYEE ?:')
            option_Label.grid(row=16,column=0,sticky=tk.W)
            submition_Label=tk.Label(top3,text='SUBMIT DATA:')
            submition_Label.grid(row=110,column=0,sticky=tk.W)
            #create entry box...........
            name_var=tk.StringVar()
            name_entrybox=ttk.Entry(top3, width=16,textvariable=name_var)
            name_entrybox.grid(row=2,column=1,pady=4,padx=4)
            gmail_var=tk.StringVar()
            gmail_entrybox=ttk.Entry(top3, width=16,textvariable=gmail_var)
            gmail_entrybox.grid(row=4,column=1,pady=4,padx=4)
            age_var=tk.StringVar()
            age_entrybox=ttk.Entry(top3, width=16,textvariable=age_var)
            age_entrybox.grid(row=6,column=1,pady=4,padx=4) 
            mobile_var=tk.StringVar()
            mobile_entrybox=ttk.Entry(top3, width=16,textvariable=mobile_var)
            mobile_entrybox.grid(row=8,column=1,pady=4,padx=4)
            gender_var=tk.StringVar()
            gender_Combobox=ttk.Combobox(top3,width=14,textvariable=gender_var,state='readonly')
            gender_Combobox['values']=('male','female','other')
            gender_Combobox.current(0)
            gender_Combobox.grid(row=10,column=1)
            option1_var1=tk.StringVar()
            option1_Combobox1=ttk.Combobox(top3,width=14,textvariable=option1_var1,state='readonly')
            option1_Combobox1['values']=('YES','NO')
            option1_Combobox1.current(0)
            option1_Combobox1.grid(row=14,column=1,pady=4,padx=4)
            option_var=tk.StringVar()
            option_Combobox=ttk.Combobox(top3,width=14,textvariable=option_var,state='readonly')
            option_Combobox['values']=('YES','NO')
            option_Combobox.current(0)
            option_Combobox.grid(row=16,column=1,pady=4,padx=4)
            #radiobutton...............
            usertype=tk.StringVar()
            radiobtn1=ttk.Radiobutton(top3, text='young age',value='young age',variable=usertype)
            radiobtn1.grid(row=12,column=1)
            radiobtn2=ttk.Radiobutton(top3, text='mid age',value='mid age',variable=usertype)
            radiobtn2.grid(row=12,column=2)
            radiobtn3=ttk.Radiobutton(top3, text='old age',value='old age',variable=usertype)
            radiobtn3.grid(row=12,column=3)
            #check button...........
            checkbtn_var1=tk.IntVar()
            checkbtn_var2=tk.IntVar()
            checkbtn1=ttk.Checkbutton(top3,text='YES',variable=checkbtn_var1)
            checkbtn1.grid(row=22,columnspan=5) 
            checkbtn2=ttk.Checkbutton(top3,text='NO',variable=checkbtn_var2)
            checkbtn2.grid(row=24,columnspan=5)
            ##create button.............
            def action():
                username=name_var.get()
                userage=age_var.get()
                usergmail=gmail_var.get()
                useroption=option1_var1.get()
                useroption=option_var.get()
                type=usertype.get()
                usergender=gender_var.get()
                usermobile=mobile_var.get()
                print(f'This person name is:-{username} and is of age :-{userage}years old and have  Gmail:- {usergmail} and is:- {type} and is permanent employee :-{useroption}  and is removed  ;-{useroption}and is :-{usergender} and its mobile number is:-{usermobile}')
                if checkbtn_var1.get()==0:
                    save='NO'
                else:
                    save='YES'
                    print(save)
                print(f'This person name is:-{username} and is of age :-{userage}years old and have  Gmail:- {usergmail} and is:- {type} and is permanent employee :-{useroption}  and is removed ;- {useroption}  and is :-{usergender} and its mobile number is:-{usermobile}')
                name_entrybox.delete(0,tk.END)
                age_entrybox.delete(0,tk.END)
                gmail_entrybox.delete(0,tk.END)
                mobile_entrybox.delete(0,tk.END)    
            
            submit_Button1=tk.Button(top3,text='submit',command=action,bg='grey')
            submit_Button1.grid(row=110,column=0) 
            submit_Button2=tk.Button(top3,text="previous",command=top3.destroy,bg='grey')
            submit_Button2.grid(row=110,column=1)                        
            submit_Button2.configure(foreground='blue') 
            submit_Button1.configure(foreground='blue')
        submit_Button=tk.Button(top3,text='EMPLOYEE ',command=open4,bg='grey')
        submit_Button.configure(foreground='blue')
        submit_Button.grid(row=1,column=0,ipadx=450,ipady=50)
###############################################################################open of administration finance window4        
        def open5():
            top3=tk.Toplevel()
            top3.geometry("1080x720")
            top3.title("WELCOME TO FINANCE SHELL")
            top3.geometry("1080x720")
#            create labels
            name_Label1=tk.Label(top3, text='PLEASE ENTER THE DETAILS AS PER GIVEN DETAILS ...............................................................................................................................................')         
            name_Label1.grid(row=0,column=0,sticky=tk.W)
            name_Label=tk.Label(top3, text='ENTER EM. NAME: ')
            name_Label.grid(row=1,column=0,sticky=tk.W)
            gmail_Label=tk.Label(top3,text='EMAIL:')
            gmail_Label.grid(row=2,column=0,sticky=tk.W)
            position_Label=tk.Label(top3,text='POSITION:')
            position_Label.grid(row=4,column=0,sticky=tk.W)
            mobile_Label=tk.Label(top3,text='MO. NUMBER:')
            mobile_Label.grid(row=6,column=0,sticky=tk.W)
            bank_Label=tk.Label(top3,text='BANK:')
            bank_Label.grid(row=8,column=0,sticky=tk.W)
            IFSCCode_Label=tk.Label(top3,text='IFSC Code:')
            IFSCCode_Label.grid(row=10,column=0,sticky=tk.W)
            accountnumber_Label=tk.Label(top3,text='ACCOUNT NUMBER:')
            accountnumber_Label.grid(row=12,column=0,sticky=tk.W)
            todate_Label=tk.Label(top3,text='TO DATE:')
            todate_Label.grid(row=14,column=0,sticky=tk.W)
            tilldate_Label=tk.Label(top3, text='TILL DATE: ')
            tilldate_Label.grid(row=16,column=0,sticky=tk.W)
            advance_Label=tk.Label(top3,text='ADVANCE:')
            advance_Label.grid(row=18,column=0,sticky=tk.W)
            due_Label=tk.Label(top3,text='DUE:')
            due_Label.grid(row=20,column=0,sticky=tk.W)
            submition_Label=tk.Label(top3,text='SUBMIT DATA:')
            submition_Label.grid(row=110,column=0,sticky=tk.W)
# entery box................................................... 
            name_var=tk.StringVar()
            name_entrybox=ttk.Entry(top3, width=16,textvariable=name_var)
            name_entrybox.grid(row=1,column=1,pady=4,padx=4)
            gmail_var=tk.StringVar()
            gmail_entrybox=ttk.Entry(top3, width=16,textvariable=gmail_var)
            gmail_entrybox.grid(row=2,column=1,pady=4,padx=4)
            position_var=tk.StringVar()
            position_entrybox=ttk.Entry(top3, width=16,textvariable=position_var)
            position_entrybox.grid(row=4,column=1,pady=4,padx=4) 
            mobile_var=tk.StringVar()
            mobile_entrybox=ttk.Entry(top3, width=16,textvariable=mobile_var)
            mobile_entrybox.grid(row=6,column=1,pady=4,padx=4)          
            bank_var=tk.StringVar()
            bank_entrybox=ttk.Entry(top3, width=16,textvariable=bank_var)
            bank_entrybox.grid(row=8,column=1,pady=4,padx=4)
            IFSCCode_var=tk.StringVar()
            IFSCCode_entrybox=ttk.Entry(top3, width=16,textvariable=IFSCCode_var)
            IFSCCode_entrybox.grid(row=10,column=1,pady=4,padx=4)
            accountnumber_var=tk.StringVar()
            accountnumber_entrybox=ttk.Entry(top3, width=16,textvariable=accountnumber_var)
            accountnumber_entrybox.grid(row=12,column=1,pady=4,padx=4) 
            todate_var=tk.StringVar()
            todate_entrybox=ttk.Entry(top3, width=16,textvariable=todate_var)
            todate_entrybox.grid(row=14,column=1,pady=4,padx=4)  
            tilldate_var=tk.StringVar()
            tilldate_entrybox=ttk.Entry(top3, width=16,textvariable=tilldate_var)
            tilldate_entrybox.grid(row=16,column=1,pady=4,padx=4)
#      combobox..............................................     
            advance_var=tk.StringVar()
            advance_Combobox=ttk.Combobox(top3,width=14,textvariable=advance_var,state='readonly')
            advance_Combobox['values']=('YES','NO')
            advance_Combobox.current(0)
            advance_Combobox.grid(row=18,column=1,pady=4,padx=4)
            due_var=tk.StringVar()
            due_Combobox=ttk.Combobox(top3,width=14,textvariable=due_var,state='readonly')
            due_Combobox['values']=('YES','NO')
            due_Combobox.current(0)
            due_Combobox.grid(row=20,column=1,pady=4,padx=4)
             ##create button.............
            def action():
                username=name_var.get()
                usergmail=gmail_var.get()
                userposition=position_var.get()
                usermobile=mobile_var.get()
                userbank=bank_var.get()
                userIFSCCode=IFSCCode_var.get()
                useraccountnumber=accountnumber_var.get()
                usertodate=todate_var.get()
                usertilldate=tilldate_var.get()
                useradvance=advance_var.get()
                userdue=due_var.get()
                print(f'{username},{usergmail},{userposition},{usermobile},{userbank},{userIFSCCode},{useraccountnumber},{usertodate},{usertilldate},{useradvance},{userdue}')
                name_entrybox.delete(0,tk.END)
                position_entrybox.delete(0,tk.END)
                gmail_entrybox.delete(0,tk.END)
                mobile_entrybox.delete(0,tk.END)    
                bank_entrybox.delete(0,tk.END)
                IFSCCode_entrybox.delete(0,tk.END)
                accountnumber_entrybox.delete(0,tk.END)
                todate_entrybox.delete(0,tk.END)  
                tilldate_entrybox.delete(0,tk.END) 
            submit_Button1=tk.Button(top3,text='submit',command=action,bg='grey')
            submit_Button1.grid(row=110,column=0) 
            submit_Button2=tk.Button(top3,text="previous",command=top3.destroy,bg='grey')
            submit_Button2.grid(row=110,column=1)                        
            submit_Button2.configure(foreground='blue') 
            submit_Button1.configure(foreground='blue')
        submit_Button=tk.Button(top3,text='FINANCE',command=open5,bg='grey')
        submit_Button.configure(foreground='blue')
        submit_Button.grid(row=2,column=0,ipadx=450,ipady=50)
##############################################################################open of administration  attendance window5                
        def open6():
            top3=tk.Toplevel()
            top3.geometry("1080x720")
            top3.title("WELCOME TO ATTENDANCE SHELL")
            top3.geometry("1080x720")            
#            create labels
            name_Label1=tk.Label(top3, text='PLEASE ENTER THE DETAILS AS PER GIVEN DETAILS ...............................................................................................................................................')         
            name_Label1.grid(row=0,column=0,sticky=tk.W)
            name_Label=tk.Label(top3, text='ENTER EM. NAME: ')
            name_Label.grid(row=1,column=0,sticky=tk.W)
            gmail_Label=tk.Label(top3,text='EMAIL:')
            gmail_Label.grid(row=2,column=0,sticky=tk.W)
            position_Label=tk.Label(top3,text='POSITION:')
            position_Label.grid(row=4,column=0,sticky=tk.W)
            mobile_Label=tk.Label(top3,text='MO. NUMBER:')
            mobile_Label.grid(row=6,column=0,sticky=tk.W)
            dateofjoin_Label=tk.Label(top3,text='DATE OF JOIN:')
            dateofjoin_Label.grid(row=8,column=0,sticky=tk.W)
            totalworkingdays_Label=tk.Label(top3,text='TOTAL WORK DONE:')
            totalworkingdays_Label.grid(row=10,column=0,sticky=tk.W)
            totalabsent_Label=tk.Label(top3,text='total ABSENT:')
            totalabsent_Label.grid(row=12,column=0,sticky=tk.W)
            presentday_Label=tk.Label(top3,text='PRESENT DAY:')
            presentday_Label.grid(row=14,column=0,sticky=tk.W)
            checkin_Label=tk.Label(top3, text='CHECK IN TIME: ')
            checkin_Label.grid(row=16,column=0,sticky=tk.W)
            checkout_Label=tk.Label(top3,text='CHECKOUT TIME:')
            checkout_Label.grid(row=18,column=0,sticky=tk.W)
            dayshift_Label=tk.Label(top3,text='DAY SHIFT:')
            dayshift_Label.grid(row=20,column=0,sticky=tk.W)
            nightshift_Label=tk.Label(top3,text='NIGHT SHIFT:')
            nightshift_Label.grid(row=22,column=0,sticky=tk.W)
            submition_Label=tk.Label(top3,text='SUBMIT DATA:')
            submition_Label.grid(row=110,column=0,sticky=tk.W)            
# entery box................................................... 
            name_var=tk.StringVar()
            name_entrybox=ttk.Entry(top3, width=16,textvariable=name_var)
            name_entrybox.grid(row=1,column=1,pady=4,padx=4)
            gmail_var=tk.StringVar()
            gmail_entrybox=ttk.Entry(top3, width=16,textvariable=gmail_var)
            gmail_entrybox.grid(row=2,column=1,pady=4,padx=4)
            position_var=tk.StringVar()
            position_entrybox=ttk.Entry(top3, width=16,textvariable=position_var)
            position_entrybox.grid(row=4,column=1,pady=4,padx=4) 
            mobile_var=tk.StringVar()
            mobile_entrybox=ttk.Entry(top3, width=16,textvariable=mobile_var)
            mobile_entrybox.grid(row=6,column=1,pady=4,padx=4)          
            dateofjoin_var=tk.StringVar()
            dateofjoin_entrybox=ttk.Entry(top3, width=16,textvariable=dateofjoin_var)
            dateofjoin_entrybox.grid(row=8,column=1,pady=4,padx=4)
            totalworkingdays_var=tk.StringVar()
            totalworkingdays_entrybox=ttk.Entry(top3, width=16,textvariable=totalworkingdays_var)
            totalworkingdays_entrybox.grid(row=10,column=1,pady=4,padx=4)
            totalabsent_var=tk.StringVar()
            totalabsent_entrybox=ttk.Entry(top3, width=16,textvariable=totalabsent_var)
            totalabsent_entrybox.grid(row=12,column=1,pady=4,padx=4)
            presentday_var=tk.StringVar()
            presentday_entrybox=ttk.Entry(top3, width=16,textvariable= presentday_var)
            presentday_entrybox.grid(row=14,column=1,pady=4,padx=4)            
#      combobox..............................................     
            checkin_var=tk.StringVar()
            checkin_Combobox=ttk.Combobox(top3,width=14,textvariable=checkin_var,state='readonly')
            checkin_Combobox['values']=('YES','NO')
            checkin_Combobox.current(0)
            checkin_Combobox.grid(row=16,column=1,pady=4,padx=4)
            checkout_var=tk.StringVar()
            checkout_Combobox=ttk.Combobox(top3,width=14,textvariable=checkout_var,state='readonly')
            checkout_Combobox['values']=('YES','NO')
            checkout_Combobox.current(0)
            checkout_Combobox.grid(row=18,column=1,pady=4,padx=4)
            dayshift_var=tk.StringVar()
            dayshift_Combobox=ttk.Combobox(top3,width=14,textvariable=dayshift_var,state='readonly')
            dayshift_Combobox['values']=('YES','NO')
            dayshift_Combobox.current(0)
            dayshift_Combobox.grid(row=20,column=1,pady=4,padx=4)
            nightshift_var=tk.StringVar()
            nightshift_Combobox=ttk.Combobox(top3,width=14,textvariable=nightshift_var,state='readonly')
            nightshift_Combobox['values']=('YES','NO')
            nightshift_Combobox.current(0)
            nightshift_Combobox.grid(row=22,column=1,pady=4,padx=4)
             ##create button.............
            def action():
                username=name_var.get()
                usergmail=gmail_var.get()
                userposition=position_var.get()
                usermobile=mobile_var.get()
                userdateofjoin=dateofjoin_var.get()
                usertotalworkingdays=totalworkingdays_var.get()
                usercheckin=checkin_var.get()
                usercheckout= checkout_var.get()
                userdayshift= dayshift_var.get()
                usernightshift=nightshift_var.get()
                usertotalabsent=totalabsent_var.get()
                userpresentday=presentday_var.get()
                print(f'{username},{usergmail},{userposition},{usermobile},{userdateofjoin},{usertotalworkingdays},{usercheckin},{usercheckout},{userdayshift},{usernightshift},{usertotalabsent},{userpresentday}')
                name_entrybox.delete(0,tk.END)
                position_entrybox.delete(0,tk.END)
                dateofjoin_entrybox.delete(0,tk.END)
                mobile_entrybox.delete(0,tk.END)
                presentday_entrybox.delete(0,tk.END)
                totalworkingdays_entrybox.delete(0,tk.END)
                totalabsent_entrybox.delete(0,tk.END)                
            submit_Button1=tk.Button(top3,text='submit',command=action,bg='grey')
            submit_Button1.grid(row=110,column=0) 
            submit_Button2=tk.Button(top3,text="previous",command=top3.destroy,bg='grey')
            submit_Button2.grid(row=110,column=1)                        
            submit_Button2.configure(foreground='blue') 
            submit_Button1.configure(foreground='blue')
        submit_Button=tk.Button(top3,text='ATTENDANCE ',command=open6,bg='grey')
        submit_Button.configure(foreground='blue')
        submit_Button.grid(row=3,column=0,ipadx=450,ipady=50) 
###############################################################################open of administration leave shell  window6      
        def open7():
            top3=tk.Toplevel()
            top3.geometry("1080x720")
            top3.title("WELCOME TO LEAVE SHELL")
            top3.geometry("1080x720")
#            create labels....................................................
            name_Label1=tk.Label(top3, text='PLEASE ENTER THE DETAILS AS PER GIVEN DETAILS ...............................................................................................................................................')         
            name_Label1.grid(row=0,column=0,sticky=tk.W)
            name_Label=tk.Label(top3, text='ENTER EM. NAME: ')
            name_Label.grid(row=1,column=0,sticky=tk.W)
            gmail_Label=tk.Label(top3,text='EMAIL:')
            gmail_Label.grid(row=2,column=0,sticky=tk.W)
            position_Label=tk.Label(top3,text='POSITION:')
            position_Label.grid(row=4,column=0,sticky=tk.W)
            mobile_Label=tk.Label(top3,text='MO. NUMBER:')
            mobile_Label.grid(row=6,column=0,sticky=tk.W)
            dateofjoin_Label=tk.Label(top3,text='DATE OF JOIN:')
            dateofjoin_Label.grid(row=8,column=0,sticky=tk.W)
            totalworkingdays_Label=tk.Label(top3,text='TOTAL WORK DONE:')
            totalworkingdays_Label.grid(row=10,column=0,sticky=tk.W)
            totalabsent_Label=tk.Label(top3,text='total ABSENT:')
            totalabsent_Label.grid(row=12,column=0,sticky=tk.W)
            reason_Label=tk.Label(top3,text='REASON TO TAKE LEAVE :')
            reason_Label.grid(row=14,column=0,sticky=tk.W)
            emergancy_Label=tk.Label(top3, text='EMERGANCY LEAVE: ')
            emergancy_Label.grid(row=16,column=0,sticky=tk.W)
            checkout_Label=tk.Label(top3,text='CHECKOUT TIME:')
            checkout_Label.grid(row=18,column=0,sticky=tk.W)
            workfromhome_Label=tk.Label(top3,text='WORK FROM HOME:')
            workfromhome_Label.grid(row=20,column=0,sticky=tk.W)            
            submition_Label=tk.Label(top3,text='SUBMIT DATA:')
            submition_Label.grid(row=110,column=0,sticky=tk.W)            
# entery box................................................... 
            name_var=tk.StringVar()
            name_entrybox=ttk.Entry(top3, width=16,textvariable=name_var)
            name_entrybox.grid(row=1,column=1,pady=4,padx=4)
            gmail_var=tk.StringVar()
            gmail_entrybox=ttk.Entry(top3, width=16,textvariable=gmail_var)
            gmail_entrybox.grid(row=2,column=1,pady=4,padx=4)
            position_var=tk.StringVar()
            position_entrybox=ttk.Entry(top3, width=16,textvariable=position_var)
            position_entrybox.grid(row=4,column=1,pady=4,padx=4) 
            mobile_var=tk.StringVar()
            mobile_entrybox=ttk.Entry(top3, width=16,textvariable=mobile_var)
            mobile_entrybox.grid(row=6,column=1,pady=4,padx=4)          
            dateofjoin_var=tk.StringVar()
            dateofjoin_entrybox=ttk.Entry(top3, width=16,textvariable=dateofjoin_var)
            dateofjoin_entrybox.grid(row=8,column=1,pady=4,padx=4)
            totalworkingdays_var=tk.StringVar()
            totalworkingdays_entrybox=ttk.Entry(top3, width=16,textvariable=totalworkingdays_var)
            totalworkingdays_entrybox.grid(row=10,column=1,pady=4,padx=4)
            totalabsent_var=tk.StringVar()
            totalabsent_entrybox=ttk.Entry(top3, width=16,textvariable=totalabsent_var)
            totalabsent_entrybox.grid(row=12,column=1,pady=4,padx=4)
            reason_var=tk.StringVar()
            reason_entrybox=ttk.Entry(top3, width=16,textvariable=reason_var)
            reason_entrybox.grid(row=14,column=1,pady=4,padx=4)            
#      combobox..............................................     
            emergancy_var=tk.StringVar()
            emergancy_Combobox=ttk.Combobox(top3,width=14,textvariable=emergancy_var,state='readonly')
            emergancy_Combobox['values']=('YES','NO')
            emergancy_Combobox.current(0)
            emergancy_Combobox.grid(row=16,column=1,pady=4,padx=4)
            checkout_var=tk.StringVar()
            checkout_Combobox=ttk.Combobox(top3,width=14,textvariable=checkout_var,state='readonly')
            checkout_Combobox['values']=('YES','NO')
            checkout_Combobox.current(0)
            checkout_Combobox.grid(row=18,column=1,pady=4,padx=4)
            workfromhome_var=tk.StringVar()
            workfromhome_Combobox=ttk.Combobox(top3,width=14,textvariable=workfromhome_var,state='readonly')
            workfromhome_Combobox['values']=('YES','NO')
            workfromhome_Combobox.current(0)
            workfromhome_Combobox.grid(row=20,column=1,pady=4,padx=4)
           
             ##create button.............
            def action():
                username=name_var.get()
                usergmail=gmail_var.get()
                userposition=position_var.get()
                usermobile=mobile_var.get()
                userdateofjoin=dateofjoin_var.get()
                usertotalworkingdays=totalworkingdays_var.get()
                userworkfromhome=workfromhome_var.get()
                usertotalabsent=totalabsent_var.get()
                useremergancyt=  emergancy_var.get()
                usertotalabsent=totalabsent_var.get()
                usercheckout=checkout_var.get()
                print(f'{username},{usergmail},{userposition},{usermobile},{userdateofjoin},{usertotalworkingdays},{usercheckout},{userworkfromhome},{useremergancyt},{usertotalabsent}')
                name_entrybox.delete(0,tk.END)
                position_entrybox.delete(0,tk.END)
                dateofjoin_entrybox.delete(0,tk.END)
                mobile_entrybox.delete(0,tk.END)
                totalworkingdays_entrybox.delete(0,tk.END)
                totalabsent_entrybox.delete(0,tk.END)                
            submit_Button1=tk.Button(top3,text='submit',command=action,bg='grey')
            submit_Button1.grid(row=110,column=0) 
            submit_Button2=tk.Button(top3,text="previous",command=top3.destroy,bg='grey')
            submit_Button2.grid(row=110,column=1)                        
            submit_Button2.configure(foreground='blue') 
            submit_Button1.configure(foreground='blue')
        submit_Button=tk.Button(top3,text='LEAVE',command=open7,bg='grey')
        submit_Button.configure(foreground='blue')
        submit_Button.grid(row=4,column=0,ipadx=450,ipady=50)
        submit_Button=tk.Button(top3,text="previous",command=top3.destroy,bg='grey')
        submit_Button.grid(row=300,column=350)                        
        submit_Button.configure(foreground='blue',bg='grey')
#        ###############################################################open of  administration performance shell window7
        def open8():
            top3=tk.Toplevel()
            top3.geometry("1080x720")
            top3.title("WELCOME TO PERFORMANCE SHELL")
            top3.geometry("1080x720")
#create labels....................................................
            name_Label1=tk.Label(top3, text='PLEASE ENTER THE DETAILS AS PER GIVEN DETAILS ...............................................................................................................................................')         
            name_Label1.grid(row=0,column=0,sticky=tk.W)
            name_Label=tk.Label(top3, text='ENTER EM. NAME: ')
            name_Label.grid(row=1,column=0,sticky=tk.W)
            gmail_Label=tk.Label(top3,text='EMAIL:')
            gmail_Label.grid(row=2,column=0,sticky=tk.W)
            position_Label=tk.Label(top3,text='POSITION:')
            position_Label.grid(row=4,column=0,sticky=tk.W)
            mobile_Label=tk.Label(top3,text='MO. NUMBER:')
            mobile_Label.grid(row=6,column=0,sticky=tk.W)
            dateofjoin_Label=tk.Label(top3,text='DATE OF JOIN:')
            dateofjoin_Label.grid(row=8,column=0,sticky=tk.W)
            totalworkingdays_Label=tk.Label(top3,text='TOTAL WORK DONE:')
            totalworkingdays_Label.grid(row=10,column=0,sticky=tk.W)
            totalabsent_Label=tk.Label(top3,text='total ABSENT:')
            totalabsent_Label.grid(row=12,column=0,sticky=tk.W)
            workingtype_Label=tk.Label(top3,text='WORKING TYPE :')
            workingtype_Label.grid(row=14,column=0,sticky=tk.W)
            promotion_Label=tk.Label(top3, text='PROMOTION:: ')
            promotion_Label.grid(row=16,column=0,sticky=tk.W)
            consideration_Label=tk.Label(top3,text='KEEP UNDER CONSIDERATION:')
            consideration_Label.grid(row=18,column=0,sticky=tk.W)
            assignatask_Label=tk.Label(top3,text='ASSIGN A TASK:')
            assignatask_Label.grid(row=20,column=0,sticky=tk.W)            
            submition_Label=tk.Label(top3,text='SUBMIT DATA:')
            submition_Label.grid(row=110,column=0,sticky=tk.W)            
# entery box................................................... 
            name_var=tk.StringVar()
            name_entrybox=ttk.Entry(top3, width=16,textvariable=name_var)
            name_entrybox.grid(row=1,column=1,pady=4,padx=4)
            gmail_var=tk.StringVar()
            gmail_entrybox=ttk.Entry(top3, width=16,textvariable=gmail_var)
            gmail_entrybox.grid(row=2,column=1,pady=4,padx=4)
            position_var=tk.StringVar()
            position_entrybox=ttk.Entry(top3, width=16,textvariable=position_var)
            position_entrybox.grid(row=4,column=1,pady=4,padx=4) 
            mobile_var=tk.StringVar()
            mobile_entrybox=ttk.Entry(top3, width=16,textvariable=mobile_var)
            mobile_entrybox.grid(row=6,column=1,pady=4,padx=4)          
            dateofjoin_var=tk.StringVar()
            dateofjoin_entrybox=ttk.Entry(top3, width=16,textvariable=dateofjoin_var)
            dateofjoin_entrybox.grid(row=8,column=1,pady=4,padx=4)
            totalworkingdays_var=tk.StringVar()
            totalworkingdays_entrybox=ttk.Entry(top3, width=16,textvariable=totalworkingdays_var)
            totalworkingdays_entrybox.grid(row=10,column=1,pady=4,padx=4)
            totalabsent_var=tk.StringVar()
            totalabsent_entrybox=ttk.Entry(top3, width=16,textvariable=totalabsent_var)
            totalabsent_entrybox.grid(row=12,column=1,pady=4,padx=4)
             
#      combobox..............................................     
            workingtype_var=tk.StringVar()
            workingtype_Combobox=ttk.Combobox(top3,width=14,textvariable=workingtype_var,state='readonly')
            workingtype_Combobox['values']=('GOOD','AVERAGE','BEST')
            workingtype_Combobox.current(0)
            workingtype_Combobox.grid(row=16,column=1,pady=4,padx=4)
            promotion_var=tk.StringVar()
            promotion_Combobox=ttk.Combobox(top3,width=14,textvariable=promotion_var,state='readonly')
            promotion_Combobox['values']=('YES','NO')
            promotion_Combobox.current(0)
            promotion_Combobox.grid(row=18,column=1,pady=4,padx=4)
            consideration_var=tk.StringVar()
            consideration_Combobox=ttk.Combobox(top3,width=14,textvariable=consideration_var,state='readonly')
            consideration_Combobox['values']=('YES','NO')
            consideration_Combobox.current(0)
            consideration_Combobox.grid(row=20,column=1,pady=4,padx=4)
            assignatask_var=tk.StringVar()
            assignatask_Combobox=ttk.Combobox(top3,width=14,textvariable=assignatask_var,state='readonly')
            assignatask_Combobox['values']=('YES','NO')
            assignatask_Combobox.current(0)
            assignatask_Combobox.grid(row=20,column=1,pady=4,padx=4)
           
             ##create button.............
            def action():
                username=name_var.get()
                usergmail=gmail_var.get()
                userposition=position_var.get()
                usermobile=mobile_var.get()
                userdateofjoin=dateofjoin_var.get()
                usertotalworkingdays=totalworkingdays_var.get()
                userworkingtype=workingtype_var.get()
                userpromotion=promotion_var.get()
                userconsideration=consideration_var.get()
                userassignatask=assignatask_var.get()               
                print(f'{username},{usergmail},{userposition},{usermobile},{userdateofjoin},{usertotalworkingdays},{userworkingtype},{userpromotion},{userconsideration},{userassignatask}')
                name_entrybox.delete(0,tk.END)
                position_entrybox.delete(0,tk.END)
                dateofjoin_entrybox.delete(0,tk.END)
                mobile_entrybox.delete(0,tk.END)
                totalworkingdays_entrybox.delete(0,tk.END)
                totalabsent_entrybox.delete(0,tk.END)                
            submit_Button1=tk.Button(top3,text='submit',command=action,bg='grey')
            submit_Button1.grid(row=110,column=0) 
            submit_Button2=tk.Button(top3,text="previous",command=top3.destroy,bg='grey')
            submit_Button2.grid(row=110,column=1)                        
            submit_Button2.configure(foreground='blue') 
            submit_Button1.configure(foreground='blue')
        
        submit_Button=tk.Button(top3,text="previous",command=top3.destroy,bg='grey')   
        submit_Button=tk.Button(top3,text='PERFORMANCE',command=open8,bg='grey')
        submit_Button.configure(foreground='blue',bg='grey')
        submit_Button.grid(row=5,column=0,ipadx=450,ipady=50) 
        
 ##################################EMPLOYEE####################################main window 1 employeee section       
        
    def open3(): 
        top2=tk.Toplevel()
        top2.geometry("1080x720")
        top2.title("WELCOME TO EMPLOYEE DASHBOARD ")
        top2.geometry("1080x720")
################################################################################OPEN OF EMPLOYEE SHELL under employee window7        
        def open9():
            top2=tk.Toplevel()
            top2.geometry("1080x720")
            top2.title("WELCOME TO EMPLOYEE SHELL")
            top2.geometry("1080x720")
              #create labels.................
            name_Label1=tk.Label(top2, text='PLEASE ENTER THE DETAILS AS PER GIVEN DETAILS ...............................................................................................................................................')         
            name_Label1.grid(row=0,column=0,sticky=tk.W)
            name_Label=tk.Label(top2, text='ENTER EM. NAME: ')
            name_Label.grid(row=1,column=0,sticky=tk.W)
            gmail_Label=tk.Label(top2,text='EMAIL:')
            gmail_Label.grid(row=1,column=0,sticky=tk.W)
            age_Label=tk.Label(top2,text='AGE:')
            age_Label.grid(row=2,column=0,sticky=tk.W)
            mobile_Label=tk.Label(top2,text='MO. NUMBER:')
            mobile_Label.grid(row=3,column=0,sticky=tk.W)
            gender_Label=tk.Label(top2,text='SEX:')
            gender_Label.grid(row=4,column=0,sticky=tk.W)
            fathername_Label=tk.Label(top2,text='FATHER NAME:')
            fathername_Label.grid(row=5,column=0,sticky=tk.W)
            mothername_Label=tk.Label(top2,text='MOTHER NAME:')
            mothername_Label.grid(row=6,column=0,sticky=tk.W)
            temparoryaddress_Label=tk.Label(top2,text='TEMPORARY ADDRESS:')
            temparoryaddress_Label.grid(row=7,column=0,sticky=tk.W)
            submition_Label=tk.Label(top2,text='SUBMIT:')
            submition_Label.grid(row=110,column=0,sticky=tk.W)
            #create entry box...........
            name_var=tk.StringVar()
            name_entrybox=ttk.Entry(top2, width=16,textvariable=name_var)
            name_entrybox.grid(row=1,column=1,pady=4,padx=4)
            gmail_var=tk.StringVar()
            gmail_entrybox=ttk.Entry(top2, width=16,textvariable=gmail_var)
            gmail_entrybox.grid(row=1,column=1,pady=4,padx=4)
            age_var=tk.StringVar()
            age_entrybox=ttk.Entry(top2, width=16,textvariable=age_var)
            age_entrybox.grid(row=2,column=1,pady=4,padx=4) 
            mobile_var=tk.StringVar()
            mobile_entrybox=ttk.Entry(top2, width=16,textvariable=mobile_var)
            mobile_entrybox.grid(row=3,column=1,pady=4,padx=4)
            gender_var=tk.StringVar()
            gender_Combobox=ttk.Combobox(top2,width=14,textvariable=gender_var,state='readonly')
            gender_Combobox['values']=('male','female','other')
            gender_Combobox.current(0)
            gender_Combobox.grid(row=4,column=1)
            option1_var1=tk.StringVar()
            option1_Combobox1=ttk.Combobox(top2,width=14,textvariable=option1_var1,state='readonly')
            option1_Combobox1['values']=('YES','NO')
            option1_Combobox1.current(0)
            option1_Combobox1.grid(row=6,column=1,pady=4,padx=4)
            option_var=tk.StringVar()
            option_Combobox=ttk.Combobox(top2,width=14,textvariable=option_var,state='readonly')
            option_Combobox['values']=('YES','NO')
            option_Combobox.current(0)
            option_Combobox.grid(row=7,column=1,pady=4,padx=4)
            #radiobutton...............
            usertype=tk.StringVar()
            radiobtn1=ttk.Radiobutton(top2, text='young age',value='young age',variable=usertype)
            radiobtn1.grid(row=5,column=1)
            radiobtn2=ttk.Radiobutton(top2, text='mid age',value='mid age',variable=usertype)
            radiobtn2.grid(row=5,column=2)
            radiobtn3=ttk.Radiobutton(top2, text='old age',value='old age',variable=usertype)
            radiobtn3.grid(row=5,column=3)
            #check button...........
            checkbtn_var1=tk.IntVar()
            checkbtn_var2=tk.IntVar()
            checkbtn1=ttk.Checkbutton(top2,text='YES',variable=checkbtn_var1)
            checkbtn1.grid(row=10,columnspan=5) 
            checkbtn2=ttk.Checkbutton(top2,text='NO',variable=checkbtn_var2)
            checkbtn2.grid(row=11,columnspan=5)
            ##create button.............
            def action():
                username=name_var.get()
                userage=age_var.get()
                usergmail=gmail_var.get()
                useroption=option1_var1.get()
                useroption=option_var.get()
                type=usertype.get()
                usergender=gender_var.get()
                usermobile=mobile_var.get()
                print(f'This person name is:-{username} and is of age :-{userage}years old and have  Gmail:- {usergmail} and is:- {type} and is permanent employee :-{useroption}  and is removed  ;-{useroption}and is :-{usergender} and its mobile number is:-{usermobile}')
                if checkbtn_var1.get()==0:
                    save='NO'
                else:
                    save='YES'
                    print(save)
                print(f'This person name is:-{username} and is of age :-{userage}years old and have  Gmail:- {usergmail} and is:- {type} and is permanent employee :-{useroption}  and is removed ;- {useroption}  and is :-{usergender} and its mobile number is:-{usermobile}')
                name_entrybox.delete(0,tk.END)
                age_entrybox.delete(0,tk.END)
                gmail_entrybox.delete(0,tk.END)
                mobile_entrybox.delete(0,tk.END)    
            
            submit_Button1=tk.Button(top2,text='submit',command=action,bg='grey')
            submit_Button1.grid(row=110,column=0) 
            submit_Button2=tk.Button(top2,text="previous",command=top2.destroy,bg='grey')
            submit_Button2.grid(row=110,column=1)                        
            submit_Button2.configure(foreground='blue') 
            submit_Button1.configure(foreground='blue')   
        submit_Button=tk.Button(top2,text='EMPLOYEE ',command=open9,bg='grey')
        submit_Button.configure(foreground='blue',bg='grey')
        submit_Button.grid(row=1,column=0,ipadx=450,ipady=50)
###############################################################################open of salary shell under employee window8        
        def open10():
            top2=tk.Toplevel()
            top2.geometry("1080x720")
            top2.title("WELCOME TO SALARY SHELL")
            top2.geometry("1080x720")
#           create labels..............................................
            name_Label1=tk.Label(top2, text='PLEASE ENTER THE DETAILS AS PER GIVEN DETAILS ...............................................................................................................................................')         
            name_Label1.grid(row=0,column=0,sticky=tk.W)
            name_Label=tk.Label(top2, text='ENTER EM. NAME: ')
            name_Label.grid(row=1,column=0,sticky=tk.W)
            gmail_Label=tk.Label(top2,text='EMAIL:')
            gmail_Label.grid(row=2,column=0,sticky=tk.W)
            position_Label=tk.Label(top2,text='POSITION:')
            position_Label.grid(row=4,column=0,sticky=tk.W)
            mobile_Label=tk.Label(top2,text='MO. NUMBER:')
            mobile_Label.grid(row=6,column=0,sticky=tk.W)
            bank_Label=tk.Label(top2,text='BANK:')
            bank_Label.grid(row=8,column=0,sticky=tk.W)
            IFSCCode_Label=tk.Label(top2,text='IFSC Code:')
            IFSCCode_Label.grid(row=10,column=0,sticky=tk.W)
            accountnumber_Label=tk.Label(top2,text='ACCOUNT NUMBER:')
            accountnumber_Label.grid(row=12,column=0,sticky=tk.W)
            address_Label=tk.Label(top2,text='ADDRESS:')
            address_Label.grid(row=14,column=0,sticky=tk.W)
            currentbalance_Label=tk.Label(top2, text='CURRENT BALANCE: ')
            currentbalance_Label.grid(row=16,column=0,sticky=tk.W)
            totalbalance_Label=tk.Label(top2,text='TOTAL BALANCE:')
            totalbalance_Label.grid(row=18,column=0,sticky=tk.W)
            dateofgetsalary_Label=tk.Label(top2,text='DATE TO GET SALLARY:')
            dateofgetsalary_Label.grid(row=20,column=0,sticky=tk.W)
            submition_Label=tk.Label(top2,text='SUBMIT DATA:')
            submition_Label.grid(row=110,column=0,sticky=tk.W)
# entery box................................................... 
            name_var=tk.StringVar()
            name_entrybox=ttk.Entry(top2, width=16,textvariable=name_var)
            name_entrybox.grid(row=1,column=1,pady=4,padx=4)
            gmail_var=tk.StringVar()
            gmail_entrybox=ttk.Entry(top2, width=16,textvariable=gmail_var)
            gmail_entrybox.grid(row=2,column=1,pady=4,padx=4)
            position_var=tk.StringVar()
            position_entrybox=ttk.Entry(top2, width=16,textvariable=position_var)
            position_entrybox.grid(row=4,column=1,pady=4,padx=4) 
            mobile_var=tk.StringVar()
            mobile_entrybox=ttk.Entry(top2, width=16,textvariable=mobile_var)
            mobile_entrybox.grid(row=6,column=1,pady=4,padx=4)          
            bank_var=tk.StringVar()
            bank_entrybox=ttk.Entry(top2, width=16,textvariable=bank_var)
            bank_entrybox.grid(row=8,column=1,pady=4,padx=4)
            IFSCCode_var=tk.StringVar()
            IFSCCode_entrybox=ttk.Entry(top2, width=16,textvariable=IFSCCode_var)
            IFSCCode_entrybox.grid(row=10,column=1,pady=4,padx=4)
            accountnumber_var=tk.StringVar()
            accountnumber_entrybox=ttk.Entry(top2, width=16,textvariable=accountnumber_var)
            accountnumber_entrybox.grid(row=12,column=1,pady=4,padx=4) 
            address_var=tk.StringVar()
            address_entrybox=ttk.Entry(top2, width=16,textvariable=address_var)
            address_entrybox.grid(row=14,column=1,pady=4,padx=4)  
            currentbalance_var=tk.StringVar()
            currentbalance_entrybox=ttk.Entry(top2, width=16,textvariable=currentbalance_var)
            currentbalance_entrybox.grid(row=16,column=1,pady=4,padx=4)
            totalbalance_var=tk.StringVar()
            totalbalance_entrybox=ttk.Entry(top2, width=16,textvariable=totalbalance_var)
            totalbalance_entrybox.grid(row=18,column=1,pady=4,padx=4)
            dateofgetsalary_var=tk.StringVar()
            dateofgetsalary_entrybox=ttk.Entry(top2, width=16,textvariable=dateofgetsalary_var)
            dateofgetsalary_entrybox.grid(row=20,column=1,pady=4,padx=4)
             ##create button.............
            def action():
                username=name_var.get()
                usergmail=gmail_var.get()
                userposition=position_var.get()
                usermobile=mobile_var.get()
                userbank=bank_var.get()
                userIFSCCode=IFSCCode_var.get()
                useraccountnumber=accountnumber_var.get()
                useraddress=address_var.get()
                usercurrentbalance=currentbalance_var.get()
                usertotalbalance=totalbalance_var.get()
                userdateofgetsalary=dateofgetsalary_var.get()
                print(f'{username},{usergmail},{userposition},{usermobile},{userbank},{userIFSCCode},{useraccountnumber},{useraddress},{usertotalbalance},{usercurrentbalance},{userdateofgetsalary}')
                name_entrybox.delete(0,tk.END)
                position_entrybox.delete(0,tk.END)
                gmail_entrybox.delete(0,tk.END)
                mobile_entrybox.delete(0,tk.END)    
                bank_entrybox.delete(0,tk.END)
                IFSCCode_entrybox.delete(0,tk.END)
                accountnumber_entrybox.delete(0,tk.END)
                address_entrybox.delete(0,tk.END)  
                currentbalance_entrybox.delete(0,tk.END) 
                totalbalance_entrybox.delete(0,tk.END) 
                dateofgetsalary_entrybox.delete(0,tk.END) 
            submit_Button1=tk.Button(top2,text='submit',command=action,bg='grey')
            submit_Button1.grid(row=110,column=0) 
            submit_Button2=tk.Button(top2,text="previous")
            submit_Button2.grid(row=110,column=1)                        
            submit_Button2.configure(foreground='blue') 
            submit_Button1.configure(foreground='blue')   
        submit_Button=tk.Button(top2,text='SALARY',command=open10,bg='grey')
        submit_Button.configure(foreground='blue')
        submit_Button.grid(row=2,column=0,ipadx=450,ipady=50)
###############################################################################open of attendance shell under employee window9        
        def open11():
            top2=tk.Toplevel()
            top2.geometry("1080x720")
            top2.title("WELCOME TO ATTENDANCE SHELL")
            top2.geometry("1080x720")
        submit_Button=tk.Button(top2,text='ATTENDANCE',command=open11,bg='grey')
        submit_Button.configure(foreground='blue')
        submit_Button.grid(row=3,column=0,ipadx=450,ipady=50)
###############################################################################open of leave shell under employee window10        
        def open12():
            top2=tk.Toplevel()
            top2.geometry("1080x720")
            top2.title("WELCOME TO LEAVE SHELL")
            top2.geometry("1080x720")
        submit_Button=tk.Button(top2,text='LEAVE ',command=open12,bg='grey')
        submit_Button.configure(foreground='blue')
        submit_Button.grid(row=4,column=0,ipadx=450,ipady=50)
        submit_Button=tk.Button(top2,text="previous",command=top2.destroy,bg='grey')
        submit_Button.grid(row=300,column=350)                        
        submit_Button.configure(foreground='blue')
###############################################################################submition of  employee mani window        
    submit_Button=tk.Button(top2,text='ADMINISTRATION ',command=open2,bg='skyblue')
    submit_Button.configure(foreground='blue')
    submit_Button.grid(row=1,column=1,ipadx=550,ipady=50) 
    submit_Button=tk.Button(top2,text='EMPLOYEE',command=open3,bg='skyblue')
    submit_Button.configure(foreground='blue')
    submit_Button.grid(row=2,column=1,ipadx=550,ipady=50)
    submit_Button=tk.Button(top2,text="previous",command=top2.destroy,bg='grey')
    submit_Button.grid(row=300,column=350)                        
    submit_Button.configure(foreground='blue')
 ##############################################################################submination of window 1                           
submit_Button=tk.Button(root,text='submit',command=open1,bg='grey')
submit_Button.configure(foreground='blue')
submit_Button.grid(row=2,column=2)                        
submit_Button=tk.Button(root,text='submit1',command=open1,bg='grey')
root.mainloop()